# Generated by Django 3.0.5 on 2020-04-29 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapsearch', '0002_map_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='footprint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='gcps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='georeferenced',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='layout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='transform',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
