# Generated by Django 3.0.5 on 2020-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsearch', '0003_auto_20200429_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
