# Generated by Django 3.0.5 on 2020-04-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapsearch', '0005_auto_20200430_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('fontheight', models.IntegerField(null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='mapsearch.Map')),
            ],
        ),
    ]
